### PR TITLE
Sorted attributes and dates as ISO strings

### PR DESCRIPTION
**Pull request by tadamic**
Hi!

I like to see my `id` first, then the rest of attributes sorted alphabetically. Also, I like dates as ISO strings.

All this is completely subjective, but if you like it, please merge :)

### CODE REVIEW

**Comment by manicmaniac** [comment]
@tadamic
Thank you for your proposal.
I don't think reordering column is necessary.
Unlike RoR, SQLAlchemy does not treat 'id' column as default primary key.
You can reorder columns in your model class, isn't it enough?
However ISO date is a good idea.

**Comment by tadamic** [comment]
Well, like i said, its subjective... Anyway, I'll remove column reordering and keep the iso dates...

**Comment by manicmaniac** [comment]
@tadamic Any updates?

**Comment by tadamic** [comment]
HI, for some reason I thought I finalized this as discussed. Thnx for reminding me :)

Anyway, it is done now: I've removed sorting and kept date formatting....

**Pull request merged**
